### ISSUE TITLE
css for links so they're less distracting

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#83]
try to style the css for links so they're less distracting.  Maybe a grayer shade of blue.

@oneilsh, are you good with css?  I'm a novice. I've started a [css-hyperlink](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/tree/css-hyperlink) branch to experiment with.  I can get the browser to recognize the hotpink css (see the screenshot).  But
1. I don't know why/where something is override the color with "#fff"
2. I change the size only on the [light theme css file](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/blob/main/assets/light-theme.scss).  But somehow it's spilling over to the [dark theme](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/blob/main/assets/dark-theme.scss).  This 2nd point may be related to Quarto, and not standard css rules.

![image](https://user-images.githubusercontent.com/1372890/227378454-02b5040c-dc52-401a-b540-6275770fb528.png)

**Comment by wibeasley** [comment]
In the meeting, @oneilsh found the special setting in quarto so it's not overwritten: https://quarto.org/docs/output-formats/html-themes.html#basic-options

I'll play around with the light & dark colors.  And see if there's a settings for light/dark themes

in _quarto.yml:
```yml
...
format:
  html:
    theme:
      light: [../assets/light-theme.scss, ../assets/tables-light.scss , zephyr]
      dark:  [../assets/dark-theme.scss , ../assets/tables-dark.scss  , slate ]
    # css: assets/citation.css
    css:
    - assets/font-awesome.css
    - ../assets/tables.css
    link-external-newwindow: true
    linkcolor: "green"
...
```
